[package]
name = "touch"
description = "Touch utility implementation"
version = "0.1.0"
authors = ["Sam Saint-Pettersen <s.stpettersen+github@gmail.com>"]

[dependencies]
clioptions = "0.1.0"
filetime = "0.1.10"
time = "0.1.35"
litepattern = "0.1.0"
